### PR TITLE
Fixes #34: Allow multiple IPs to be considered local

### LINKED ISSUE #34: Multipe ip : can't check localAlterncDomain
In some case we can have multiple IP on server (failover, ....)

isLocalAlterncDomain method check only L_PUBLIC_IP value. Should more complete and check ip add values

### PR DESCRIPTION
**Pull request by GuillaumeFromage**
Hi, we've have a couple of setups where we use multiple IPs, say when we have multiple webnodes or caching enabled. Its nice to have a way of expanding what m_certbot considers "local".

### CODE REVIEW

**Comment by camlafit** [comment]
Hello

How do define the global $L_OTHER_IPS ? How is it set (string with comma, array, ...) ?
You can simplifiy the test setting in all case $arr value

**Comment by GuillaumeFromage** [comment]
Hi Cam,

The uppercase L_BLAH_BLAH are taken straight from the local.sh (as BLAH_BLAH=xyz) in the bootstrap process. This way it adds an optional way of having more custom setup without having to change code, therefore, I wouldn't want to define it as a PHP construct. Maybe it should be a variable, but I feel mostly sysadmins will knowingly change such a value (say putting a site behind a caching site, etc). 

Lemme know if that clarifies the intent.

G

**Comment by camlafit** [comment]
Hello

Perfect I've forgotten this feature.
Rest code test simplification with setting $arr by default with  $L_PUBLIC_IP

**Comment by GuillaumeFromage** [comment]
Hi Cam, 

I've simplified the code and made some tests to make sure that everything compiles and runs properly. 

G

**Comment by kienanstewart** [comment]
Hmm I think I merged this by accident. Let me check

**Comment by kienanstewart** [comment]
Huh weird, my push to koumbit/master closed this pull request but it's not in alternc/master. I will re-open a PR

**Pull request closed without merging**
